server:
  port: 8002
spring:
  application:
    name: short-link-admin
  datasource:
    username: root
    password: javacppgorust
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 192.168.81.130
      port: 6379
      password: javacppgorust
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1 #单位是秒
    max-access-count: 3 #一秒内同一个用户最多能操作3次

