server:
  port: 8001
spring:
  application:
    name: short-link-project
  datasource:
    username: root
    password: javacppgorust
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
    # ShardingSphere 配置文件路径
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 192.168.81.130
      port: 6379
      password: javacppgorust
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087
  goto-domain:
    white-list:
      enable: true
      names: '百度,必应,哔哩哔哩,牛客,CSDN,力扣,ACWing,语雀,知乎,小林coding,JavaGuide,'
      details:
        - baidu.com
        - bing.com
        - bilibili.com
        - nowcoder.com
        - csdn.net
        - leetcode.cn
        - acwing.com
        - yuque.com
        - zhihu.com
        - xiaolincoding.com
        - javaguide.cn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml