server:
  port: 8001
spring:
  datasource:
    username: root
    password: javacppgorust
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
    # ShardingSphere 配置文件路径
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 192.168.81.130
      port: 6379
      password: javacppgorust
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml